# Generated by Django 5.0.6 on 2024-07-07 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_remove_issue_author_remove_issue_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6)),
                ('type', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('task', 'Task')], max_length=7)),
                ('status', models.CharField(choices=[('to do', 'To Do'), ('in progress', 'In Progress'), ('finished', 'Finished')], max_length=11)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_author', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_issue', to='projects.project')),
            ],
        ),
    ]
