# Generated by Django 5.0.6 on 2024-07-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
