# Generated by Django 5.0.6 on 2024-07-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='contributors',
        ),
    ]
