# Generated by Django 5.0.6 on 2024-07-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_issue_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default='2024-06-26 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default='2024-06-26 12:00:00'),
            preserve_default=False,
        ),
    ]
