# Generated by Django 5.0.6 on 2024-07-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comment_created_time_issue_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='author',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
